"""
Customer Intelligence Agent
Synthesizes customer segments, price sensitivity, purchase behavior, and funnel drop-offs.
"""

from typing import Dict, Any, List


class CustomerIntelligenceAgent:
    """Models consumer segments, behavioral attributes, and journey stages."""

    async def analyze_customer_demand(
        self,
        category: str,
        subcategory: str,
    ) -> Dict[str, Any]:
        """Synthesize customer segments and customer journey funnel."""
        return {
            "segments": [
                {
                    "id": "seg_prof",
                    "name": "Working Professionals",
                    "icon": "Briefcase",
                    "demand_signal": "high",
                    "typical_spend": 3800.0,
                    "typical_spend_range": {"min": 2500, "max": 6500},
                    "price_sensitivity": "low",
                    "purchase_frequency": "3-4 times/year",
                    "preferences": ["Contemporary Style", "All-day Ergonomics", "Brand Heritage", "Durable Materials"],
                    "motivations": ["Office & casual hybrid wear", "Social signaling", "Comfort for long commutes"],
                    "objections": ["High price without premium materials", "Limited arch support", "Slow delivery"],
                    "discovery_channels": ["Instagram Ads", "Inorbit/Nexus Mall Storefronts", "Peer Word of Mouth"],
                    "purchase_triggers": ["Salary disbursement weekend", "New collection launch", "Sale season"],
                    "repeat_purchase_signal": "high",
                    "fit_score": 92.0,
                    "evidence_type": "modeled",
                    "confidence": "high",
                },
                {
                    "id": "seg_stud",
                    "name": "Students & Gen Z",
                    "icon": "GraduationCap",
                    "demand_signal": "high",
                    "typical_spend": 1600.0,
                    "typical_spend_range": {"min": 800, "max": 2500},
                    "price_sensitivity": "high",
                    "purchase_frequency": "2-3 times/year",
                    "preferences": ["Bold Aesthetics", "Viral Streetwear Trends", "Lightweight Canvas"],
                    "motivations": ["Campus fashion", "Instagram/TikTok photo shoots", "Affordable style"],
                    "objections": ["Strict budget constraints", "Durability concerns with cheap alternatives"],
                    "discovery_channels": ["Instagram Reels", "YouTube Sneaker Reviews", "Campus Ambassadors"],
                    "purchase_triggers": ["College festival season", "Festival discounts", "Influencer promo codes"],
                    "repeat_purchase_signal": "medium",
                    "fit_score": 65.0,
                    "evidence_type": "modeled",
                    "confidence": "high",
                },
                {
                    "id": "seg_fam",
                    "name": "Families & Parents",
                    "icon": "Users",
                    "demand_signal": "medium",
                    "typical_spend": 2200.0,
                    "typical_spend_range": {"min": 1200, "max": 3500},
                    "price_sensitivity": "medium",
                    "purchase_frequency": "2 times/year",
                    "preferences": ["Longevity & Wear Resistance", "Value for Money", "Easy Maintenance"],
                    "motivations": ["Functional everyday utility", "School/festive occasions"],
                    "objections": ["Expensive seasonal replacements", "Lack of wide-width options"],
                    "discovery_channels": ["Google Local Search", "Family Mall Shopping Trips", "Traditional Word of Mouth"],
                    "purchase_triggers": ["Back to school season", "Diwali & Eid shopping festivals"],
                    "repeat_purchase_signal": "medium",
                    "fit_score": 45.0,
                    "evidence_type": "modeled",
                    "confidence": "high",
                },
                {
                    "id": "seg_prem",
                    "name": "Premium Consumers & Collectors",
                    "icon": "Diamond",
                    "demand_signal": "medium",
                    "typical_spend": 6500.0,
                    "typical_spend_range": {"min": 4500, "max": 15000},
                    "price_sensitivity": "low",
                    "purchase_frequency": "5-6 times/year",
                    "preferences": ["Limited Drop Exclusivity", "Full-grain Leather", "Artisanal Detailing"],
                    "motivations": ["Sneaker culture passion", "Uniqueness and exclusivity", "Investment/resale"],
                    "objections": ["Mass market dilution", "Counterfeit concerns", "Lack of provenance"],
                    "discovery_channels": ["Discord Sneaker Communities", "Specialty Boutique Popups", "Sneakerhead Meetups"],
                    "purchase_triggers": ["Limited edition raffle drop", "Designer collaboration releases"],
                    "repeat_purchase_signal": "high",
                    "fit_score": 88.0,
                    "evidence_type": "modeled",
                    "confidence": "high",
                },
                {
                    "id": "seg_fit",
                    "name": "Fitness & Active Enthusiasts",
                    "icon": "Dumbbell",
                    "demand_signal": "high",
                    "typical_spend": 3200.0,
                    "typical_spend_range": {"min": 2000, "max": 6000},
                    "price_sensitivity": "medium",
                    "purchase_frequency": "3-4 times/year",
                    "preferences": ["Cushioning Technology", "Breathable Mesh", "Traction & Stability"],
                    "motivations": ["Gym workouts", "Morning runs at KBR Park", "Marathon training"],
                    "objections": ["Premature sole wear", "Heaviness of the shoe"],
                    "discovery_channels": ["Fitness Influencers", "Running Club Partnerships", "CultFit/Gym Noticeboards"],
                    "purchase_triggers": ["New Year fitness resolutions", "Hyderabad Marathon registration"],
                    "repeat_purchase_signal": "high",
                    "fit_score": 78.0,
                    "evidence_type": "modeled",
                    "confidence": "high",
                },
            ],
            "journey_funnel": [
                {"stage": "Discovery", "percentage": 100, "description": "Top-of-funnel brand reach via social & search"},
                {"stage": "Consideration", "percentage": 65, "description": "Browsing catalog, reading reviews, checking specs"},
                {"stage": "Price Check", "percentage": 55, "description": "Comparing price-to-value against competitors"},
                {"stage": "Competitor Comparison", "percentage": 40, "description": "Evaluating alternatives (Nike, Puma, etc.)"},
                {"stage": "Purchase Decision", "percentage": 28, "description": "Completed checkout or retail point-of-sale"},
                {"stage": "Repeat Purchase", "percentage": 18, "description": "Repurchase within 9 months"},
            ],
            "demographic_distribution": [
                {"segment": "Working Professionals", "percentage": 35},
                {"segment": "Students & Gen Z", "percentage": 25},
                {"segment": "Fitness Enthusiasts", "percentage": 20},
                {"segment": "Premium Consumers", "percentage": 12},
                {"segment": "Families", "percentage": 8},
            ]
        }
